//! NetworkManager VPN Plugin service for CoreVPN.
//!
//! Registers on the system D-Bus as `org.freedesktop.NetworkManager.corevpn`
//! and implements the `org.freedesktop.NetworkManager.VPN.Plugin` interface.

mod config;
mod plugin;

use anyhow::{Context, Result};
use tracing::info;
use zbus::connection::Builder;

use plugin::{NM_VPN_STATE_INIT, OBJECT_PATH, VpnPlugin};

const BUS_NAME: &str = "org.freedesktop.NetworkManager.corevpn";

#[tokio::main]
async fn main() -> Result<()> {
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("info")),
        )
        .with_target(true)
        .init();

    info!("nm-corevpn-service {} starting", env!("CARGO_PKG_VERSION"));

    let plugin = VpnPlugin::new();

    let conn = Builder::system()
        .context("Failed to connect to system D-Bus")?
        .name(BUS_NAME)
        .context("Failed to request bus name")?
        .serve_at(OBJECT_PATH, plugin)
        .context("Failed to serve VPN plugin at object path")?
        .build()
        .await
        .context("Failed to build D-Bus connection")?;

    info!(
        "Registered on system bus as {} at {}",
        BUS_NAME, OBJECT_PATH
    );

    // Emit initial StateChanged(INIT) using the generated signal trait
    {
        let iface_ref = conn
            .object_server()
            .interface::<_, VpnPlugin>(OBJECT_PATH)
            .await
            .context("Failed to get interface reference")?;

        // The VpnPluginSignals trait is generated by the #[zbus::interface] macro
        // and implemented for InterfaceRef<VpnPlugin>
        use plugin::VpnPluginSignals as _;
        iface_ref
            .state_changed(NM_VPN_STATE_INIT)
            .await
            .context("Failed to emit initial StateChanged")?;
    }

    info!("Plugin ready, waiting for NetworkManager commands...");

    // Run forever — NM manages the lifecycle via D-Bus activation
    std::future::pending::<()>().await;

    #[allow(unreachable_code)]
    Ok(())
}
